### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ProjectEagler** [ProjectEagler/ProjectEaglerV1#1]
HTML:
```html
<!DOCTYPE html>
<html>
<head>
  <title>EaglerCraft Home</title>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <header>
    <h1>Welcome to EaglerCraft</h1>
    <nav>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">1.8 EaglerCraft</a></li>
        <li><a href="#">1.5.2 EaglerCraft</a></li>
        <li><a href="#">1.3 EaglerCraft</a></li>
      </ul>
    </nav>
  </header>
  
  <section>
    <h2>About EaglerCraft</h2>
    <p>EaglerCraft is a popular Minecraft server with multiple versions available for players to enjoy.</p>
  </section>
  
  <section>
    <h2>Features</h2>
    <ul>
      <li>Custom plugins</li>
      <li>Active community</li>
      <li>Regular events and competitions</li>
      <li>Support for multiple Minecraft versions</li>
    </ul>
  </section>
  
  <footer>
    <p>&copy; 2022 EaglerCraft. All rights reserved.</p>
  </footer>
</body>
</html>
```

CSS (styles.css):
```css
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
}

header {
  background-color: #333;
  color: #fff;
  padding: 20px;
}

nav ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}

nav ul li {
  display: inline;
  margin-right: 10px;
}

nav ul li a {
  color: #fff;
  text-decoration: none;
}

section {
  padding: 20px;
}

footer {
  background-color: #333;
  color: #fff;
  padding: 10px;
  text-align: center;
}
```
